// Client-side mirror of the backend config defaults (functions/src/config.js).
// Used as a fallback so the dashboard renders fully even before the
// config/global doc exists or Firestore rules are deployed. Once the real doc
// is readable, the live snapshot replaces this.
export const DEFAULT_CONFIG = {
  tasks: {
    tweet: true,
    follow_x: true,
    follow_ig: true,
    swap: true,
    faucet: true,
    tx: true,
    medium: true,
    youtube: true,
    tiktok: true,
    instagram: true,
    review: true,
  },
  points: {
    medium: 100,
    youtube: 80,
    tiktok: 50,
    instagram: 50,
    review: 40,
    swap: 30,
    faucet: 20,
    tx: 15,
    tweet: 10,
    follow_x: 15,
    follow_ig: 15,
  },
  locks: { swapHrs: 12, faucetHrs: 24, txHrs: 1, tweetMins: 30 },
  requiresApproval: { medium: true, youtube: true, tiktok: false, instagram: false, review: false },
  referral: { enabled: true, percent: 10 },
  faucet: { amountPex: "0.05" },
  tx: { amountPex: "0.0004" },
  leaderboard: {
    enabled: true,
    rewards: { rank1: 200, rank2: 150, rank3: 100, top10: 75, top50: 50, top100: 30 },
  },
  ambassador: {
    enabled: true,
    postPoints: 25,
    weeklyPostCap: 7,
    tiers: { rising: 500, lead: 5000, champion: 10000 },
    tierBonus: { rising: 2000, lead: 20000, champion: 50000 },
    tierMultiplier: { ambassador: 1, rising: 1.1, lead: 1.25, champion: 1.5 },
    ambassadorReferralPercent: 15,
    teamSharePercent: 3,
    sponsorMilestones: { m1: 100, m2: 500, m3: 1000 },
    sponsorMilestoneBonus: { m1: 1000, m2: 3000, m3: 5000 },
    activityMin: 4,
    boardMemberPoints: 10,
  },
};
